name: sizzle_lints
description: A bunch of strict rules for Dart and Flutter projects.
repository: https://github.com/blazeltd/sizzle_lints/tree/master/packages/purple_lints
version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"
