name: sizzle_lints
description: A bunch of strict rules for Dart and Flutter projects.
repository: https://github.com/sizzleco/sizzle_lints
version: 2.1.2

environment:
  sdk: ">=3.0.0 <4.0.0"
dev_dependencies:
  dart_code_metrics_presets: ^2.16.0
